import { DamageCalculation, PokemonType } from "./types";

export const POKE_API_BASE_URL = "https://pokeapi.co/api/v2/";
export const SPRITE_FRONT_DEFAULT_BASE_URL =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/";

export const MAX_POKEMON_PARTY_SIZE = 6;

export const POKEMON_TYPE_COLOR_MAP: Record<PokemonType, string> = {
  [PokemonType.Normal]: "9FA19F",
  [PokemonType.Fighting]: "FF8000",
  [PokemonType.Flying]: "81B9EF",
  [PokemonType.Poison]: "9141CB",
  [PokemonType.Ground]: "915121",
  [PokemonType.Rock]: "AFA981",
  [PokemonType.Bug]: "91A119;",
  [PokemonType.Ghost]: "704170",
  [PokemonType.Steel]: "60A1B8",
  [PokemonType.Fire]: "E62829",
  [PokemonType.Water]: "2980EF",
  [PokemonType.Grass]: "3FA129",
  [PokemonType.Electric]: "FAC000",
  [PokemonType.Psychic]: "EF4179",
  [PokemonType.Ice]: "3DCEF3",
  [PokemonType.Dragon]: "5060E1",
  [PokemonType.Dark]: "624D4E",
  [PokemonType.Fairy]: "EF70EF",
};

export const DAMAGE_MATRIX: Record<
  PokemonType,
  Partial<Record<PokemonType, DamageCalculation>>
> = {
  [PokemonType.Normal]: {
    [PokemonType.Rock]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ghost]: DamageCalculation.NO_EFFECT,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Fighting]: {
    [PokemonType.Normal]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Ice]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Dark]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Flying]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Poison]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Bug]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Psychic]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fairy]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ghost]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Flying]: {
    [PokemonType.Fighting]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Bug]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Electric]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Poison]: {
    [PokemonType.Grass]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fairy]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Poison]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ground]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ghost]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Ground]: {
    [PokemonType.Poison]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Electric]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Bug]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Flying]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Rock]: {
    [PokemonType.Flying]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Bug]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Ice]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fighting]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ground]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Bug]: {
    [PokemonType.Grass]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Psychic]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Dark]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fighting]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Flying]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Poison]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ghost]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fairy]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Ghost]: {
    [PokemonType.Ghost]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Psychic]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Dark]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Normal]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Steel]: {
    [PokemonType.Rock]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Ice]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fairy]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Water]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Electric]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Fire]: {
    [PokemonType.Bug]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Ice]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Water]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Dragon]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Water]: {
    [PokemonType.Ground]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Water]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Dragon]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Grass]: {
    [PokemonType.Ground]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Rock]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Water]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Flying]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Poison]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Bug]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Dragon]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Electric]: {
    [PokemonType.Flying]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Water]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Electric]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Dragon]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ground]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Psychic]: {
    [PokemonType.Fighting]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Poison]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Psychic]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Dark]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Ice]: {
    [PokemonType.Flying]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Ground]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Grass]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Dragon]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Water]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Ice]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Dragon]: {
    [PokemonType.Dragon]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fairy]: DamageCalculation.NO_EFFECT,
  },
  [PokemonType.Dark]: {
    [PokemonType.Ghost]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Psychic]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Fighting]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Dark]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fairy]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
  [PokemonType.Fairy]: {
    [PokemonType.Fighting]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Dragon]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Dark]: DamageCalculation.SUPER_EFFECTIVE,
    [PokemonType.Poison]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Steel]: DamageCalculation.NOT_VERY_EFFECTIVE,
    [PokemonType.Fire]: DamageCalculation.NOT_VERY_EFFECTIVE,
  },
};
